### ISSUE TITLE
bug report: office-addin-generator.iZe

### ISSUE THREAD

**Issue by xuruiyao-msft** [OfficeDev/teams-toolkit#12126]
An unexpected error has occurred while performing the unknown task. {"stack":"Error: dest already exists.\n    at c:\\Users\\xuruiyao.REDMOND\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.8.1\\out\\src\\extension.js:20:3716\n    at c:\\Users\\xuruiyao.REDMOND\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.8.1\\out\\src\\extension.js:14:393787","message":"dest already exists."}

stack:
iZe: An unexpected error has occurred while performing the unknown task. {"stack":"Error: dest already exists.\n    at c:\\Users\\xuruiyao.REDMOND\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.8.1\\out\\src\\extension.js:20:3716\n    at c:\\Users\\xuruiyao.REDMOND\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.8.1\\out\\src\\extension.js:14:393787","message":"dest already exists."}
    at Object.I9s (<REDACTED: user-file-path>/extension.js:61:25246)
    at Function.doScaffolding (<REDACTED: user-file-path>/extension.js:712:83342)
    at J9r.post (<REDACTED: user-file-path>/extension.js:712:84837)
    at J9r.run (<REDACTED: user-file-path>/extension.js:527:65440)
    at J9r.<anonymous> (<REDACTED: user-file-path>/extension.js:527:39203)
    at Fte.create (<REDACTED: user-file-path>/extension.js:728:6856)
    at Fte.<anonymous> (<REDACTED: user-file-path>/extension.js:527:39203)
    at Fte.<anonymous> (<REDACTED: user-file-path>/extension.js:14:392346)
    at Cf.createProject (<REDACTED: user-file-path>/extension.js:833:16006)
    at Cf.<anonymous> (<REDACTED: user-file-path>/extension.js:792:498836)
    at Cf.H3c (<REDACTED: user-file-path>/extension.js:796:20152)
    at Cf.<anonymous> (<REDACTED: user-file-path>/extension.js:14:392346)
    at A6 (<REDACTED: user-file-path>/extension.js:1656:17197)
    at Object.O0t [as callback] (<REDACTED: user-file-path>/extension.js:1678:16192)
    at e.runCommand (<REDACTED: user-file-path>/extension.js:1656:15373)
    at f.h (<REDACTED: user-file-path>/Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:204392)
    at f.h (<REDACTED: user-file-path>/Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:204392)

**Comment by jayzhang** [comment]
@xuruiyao-msft Can you provide the reproduce steps and the version of TTK?

**Comment by xuruiyao-msft** [comment]
My version of TTK is v5.8.1. The steps to reproduce the issue are listed below, but the issue only occurs under my environment. I asked several colleagues to do the same operation and without any blockings to create a new project.

The steps:

1. intall teams toolkit
2. create a new app -> outlook addin -> taskpane -> default folder -> input a project name
3. the error pops up complains the dest path already exsits. Actually the project is created successfully under the path. It seems like the project is created twice and fails for the second time. I am not sure yet just guess. And It only occurs to me which is confusing.

**Comment by jayzhang** [comment]
@xuruiyao-msft Thanks, we will try to reproduce the issue and investigate it.

**Comment by wh-alice** [comment]
Close stale issues. Please create new issue then we can support.
