### ISSUE TITLE
Teams App Test Tool PayloadTooLargeError

### ISSUE THREAD

**Issue by alyssa1303** [OfficeDev/teams-toolkit#12269]
**Describe the bug**
When trying to render markdown result using the Teams App Test Tool to test in web browser, I came into this issue. My guess is the response I'm trying to return includes a hard-coded image and quite a few text, which leads to this issue. Wondering if the tool can increase the payload limit to address this?

```
log Listening on 33797
log Teams App Test Tool is being launched for you to debug the Teams app: http://localhost:33797
debug started web socket client
debug started web socket client
error PayloadTooLargeError: request entity too large
    at readStream (/home/alyssa/.fx/bin/testTool/0.2.1/node_modules/@microsoft/teams-app-test-tool/dist/index.js:8:719939)
    at getRawBody (/home/alyssa/.fx/bin/testTool/0.2.1/node_modules/@microsoft/teams-app-test-tool/dist/index.js:8:719319)
    at read (/home/alyssa/.fx/bin/testTool/0.2.1/node_modules/@microsoft/teams-app-test-tool/dist/index.js:8:51157)
    at jsonParser (/home/alyssa/.fx/bin/testTool/0.2.1/node_modules/@microsoft/teams-app-test-tool/dist/index.js:8:54317)
    at Layer.handle [as handle_request] (/home/alyssa/.fx/bin/testTool/0.2.1/node_modules/@microsoft/teams-app-test-tool/dist/index.js:8:269610)
    at next (/home/alyssa/.fx/bin/testTool/0.2.1/node_modules/@microsoft/teams-app-test-tool/dist/index.js:8:271604)
    at Route.dispatch (/home/alyssa/.fx/bin/testTool/0.2.1/node_modules/@microsoft/teams-app-test-tool/dist/index.js:8:271640)
    at Layer.handle [as handle_request] (/home/alyssa/.fx/bin/testTool/0.2.1/node_modules/@microsoft/teams-app-test-tool/dist/index.js:8:269610)
    at /home/alyssa/.fx/bin/testTool/0.2.1/node_modules/@microsoft/teams-app-test-tool/dist/index.js:8:265170
    at param (/home/alyssa/.fx/bin/testTool/0.2.1/node_modules/@microsoft/teams-app-test-tool/dist/index.js:8:266755)
```

**To Reproduce**
1. Create a message with lots of text and a hard-coded image
2. Return the message as type `MessageFactory.text`
```
# python example
message = MessageFactory.text(content)
await context.send_activity(message)
```

**Expected behavior**
The test tool app is able to render the message

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 Enterprise (WSL Ubuntu 22.04)
 - Version [e.g. 22] Teams Toolkit v5.8.1

**CLI Information (please complete the following information):**

**Additional context**

**Comment by qinezh** [comment]
Hi @alyssa1303 , have you tried to debug your app in Teams client, and does it work as expected?
