### ISSUE TITLE
Teams Toolkit publish option does not work correctly

### ISSUE THREAD

**Issue by say-brad** [OfficeDev/teams-toolkit#12518]
**Describe the bug**
We have created Azure Open AI Bot and published using the teams option which recommended using team tool kit and publishing the bot via teams do not provide any response.

**To Reproduce**
Steps to reproduce the behavior: (please see attached word document for reproducing the error)
[Create an Azure Bot in Azure Portal.docx]
(https://github.com/user-attachments/files/17368494/Create.an.Azure.Bot.in.Azure.Portal.docx)

**Expected behavior**
The bot receive messages and does not responds the message and also receive a 401 message.

**Screenshots**
![Screenshot 2024-10-14 113458](https://github.com/user-attachments/assets/12f62f27-a21b-4a0b-8f35-384fbb01bc09)

**VS Code Extension Information (please complete the following information):**
Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**CLI Information (please complete the following information):**

**Additional context**
We already have a ticket with Microsoft Azure AI Studio | 2410010010003807

**Comment by yukun-dong** [comment]
Hi @say-brad ,
Your repro steps seems nothing to do with Teams Toolkit. Can you try using Teams Toolkit's command: "Provision", "Deploy" and then see again if there are any issues?

**Comment by say-brad** [comment]
Hello Yashika,

can you follow below steps and update the thread?

Thanks, Sayee
________________________________

**Comment by iamyashikagoyal** [comment]
I am following the steps, but I am still receiving the error, 

FOR TESTTOOL:
Everything is working!

FOR LOCAL:
If i say hi, it is perfectly responding, Hello, How may i assist you today. But, 
I can see in the Terminal that If i am asking the bot any question related to the data we have fed, It is giving us the answers, but in the Output it throws an error: 
![Screenshot 2024-10-17 075903](https://github.com/user-attachments/assets/4db57298-04e5-4709-8197-c9d190bef737)
![image](https://github.com/user-attachments/assets/07f0862f-1248-40f3-9503-7a6c910fb2da)

FOR DEV:
I can only see that even if i write hi or anything, i am recieving "Bot encountered an error" in the chat window.
For your refernece, this is what it looks like:
![Screenshot 2024-10-17 083240](https://github.com/user-attachments/assets/7ec023fd-cbfa-418c-881c-6608a9958ab8)

**Comment by swatDong** [comment]
From your log, it seems you have unhandled **azureopenai:app:error**
<img width="587" alt="image" src="https://github.com/user-attachments/assets/fa3542e9-b7e1-4edd-bee3-6c0e0e9cee77">


By default teams toolkit app handles errors in `adapter.onTurnError` [sample code like this](https://github.com/OfficeDev/teams-toolkit/blob/dev/templates/js/default-bot/index.js#L27-L40)

You can also adjust the error handling code to add your own logic.

**Comment by iamyashikagoyal** [comment]
import {
    OpenAIModel,
    PromptManager,
    ActionPlanner,
    Application,
    TurnState,
    TeamsAdapter,
    FeedbackLoopData
} from '@microsoft/teams-ai';
import { DefaultAzureCredential, getBearerTokenProvider } from '@azure/identity';
import { ConfigurationServiceClientCredentialFactory, MemoryStorage, TurnContext } from 'botbuilder';
import axios from 'axios';
import path from 'path';
import debug from 'debug';

const error = debug('azureopenai:app:error');
error.log = console.log.bind(console);

interface ConversationState {}
type ApplicationTurnState = TurnState<ConversationState>;

const adapter = new TeamsAdapter(
    {},
    new ConfigurationServiceClientCredentialFactory({
        MicrosoftAppId: process.env.BOT_ID,
        MicrosoftAppPassword: process.env.BOT_PASSWORD,
        MicrosoftAppTenantId: process.env.BOT_TENANT_ID,
        MicrosoftAppType: process.env.BOT_TYPE
    })
);

// Create AI components
const model = new OpenAIModel({
    // Azure OpenAI Support
    azureDefaultDeployment: process.env.AZURE_OPENAI_DEPLOYMENT!,
    azureEndpoint: process.env.AZURE_OPENAI_ENDPOINT!,
    azureApiVersion: '2024-02-15-preview',
    azureADTokenProvider: getBearerTokenProvider(
        new DefaultAzureCredential(),
        'https://cognitiveservices.azure.com/.default'
    ),

    // Request logging
    logRequests: true,
    useSystemMessages: true,
    requestConfig: {
        headers: {
            'x-ms-useragent': adapter.userAgent
        }
    }
});

const prompts = new PromptManager({
    promptsFolder: path.join(__dirname, '../src/prompts')
});

const planner = new ActionPlanner({
    model,
    prompts,
    defaultPrompt: 'chat'
});

// Define storage and application
const storage = new MemoryStorage();
export const app = new Application<ApplicationTurnState>({
    adapter,
    storage,
    ai: {
        planner: planner,
        enable_feedback_loop: true
    }
});

app.conversationUpdate('membersAdded', async (context: TurnContext) => {
    await context.sendActivity(
        "Welcome! I'm a conversational bot that can tell you about your data. You can also type `/clear` to clear the conversation history."
    );
});

app.message('/clear', async (context: TurnContext, state: TurnState) => {
    state.deleteConversationState();
    await context.sendActivity("New chat session started: Previous messages won't be used as context for new queries.");
});

app.error(async (context: TurnContext, err: any) => {
    // This check writes out errors to console log .vs. app insights.
    // NOTE: In production environment, you should consider logging this to Azure
    //       application insights.
    error(`[onTurnError] unhandled error: ${err}`);

    if (err instanceof axios.AxiosError) {
        error(err.toJSON());
        error(err.response?.data);
    } else {
        error(err);
    }

    // Send a trace activity, which will be displayed in Bot Framework Emulator
    await context.sendTraceActivity(
        'OnTurnError Trace',
        `${err}`,
        'https://www.botframework.com/schemas/error',
        'TurnError'
    );

    // Send a message to the user
    await context.sendActivity('The bot encountered an error or bug.');
    await context.sendActivity('To continue to run this bot, please fix the bot source code.');
});

app.feedbackLoop(async (_context: TurnContext, _state: TurnState, feedbackLoopData: FeedbackLoopData) => {
    if (feedbackLoopData.actionValue.reaction === 'like') {
        console.log('👍');
    } else {
        console.log('👎');
    }
});




**@swatDong The code came already setup when i downloaded the zip from Azure AI Studio, It shows citation.appearance.abstract exceeds the length limit. Is there anything in specific you want me to change?**

**Comment by IAM5K** [comment]
If you don want to send errors to user, comment these lines 
![image](https://github.com/user-attachments/assets/8143904e-5753-49bf-b061-69f9974eb2ac)

More over if you want to handle the error you need to look into the function throwing error.

**Comment by iamyashikagoyal** [comment]
@IAM5K i have already tried making changing to already present code. The problem is not it is giving me error, the problem is, because refereces are included in my answer, if the character limit goes up than 480, it crashes to theow error. It is handeling the error. I want to get rid of citations length limit exceeded error.

**Comment by IAM5K** [comment]
If possible please share your repo /code or share the source from where you cloned. I can check and let you know the possible solution

**Comment by iamyashikagoyal** [comment]
@IAM5K I created my bot on Azure AI Studio. And from there as a way to deploy i got the option to deploy it as a Team App. I clicked on it, and a zip file got downloaded.

**Comment by adashen** [comment]
It seems the bug is caused by the source code in Open AI Bot Sample. So created the issue at https://github.com/microsoft/teams-ai/issues/2132 Please track there.

**Comment by iamyashikagoyal** [comment]
@adashen Our bot wont be useful without citations. I need citations.

**Comment by KylerLas** [comment]
@iamyashikagoyal I was experiencing the same issue, what you need to do is update your openai package by using npm update openai@latest, and then update the @microsoft/teams-ai package. You'll see it jump from 1.3.1 to 1.5.1 which is where they have resolved the citation limit. 

However, 1.5.1 introduces a new bug where the citations are no longer a hyperlink and instead bugged display text such as "[doc1]" but you temporarily add a workaround by saying in your system prompt something like "After every citation include the document title in parathesis"

**Comment by iamyashikagoyal** [comment]
@adashen Hi, I tried this, but my bot in Dev is still not responding. 
**Problem:** Before even asking anything, bot says "Bot encountered an error" in the chat window.
For your refernece, this is what it looks like:

![image](https://github.com/user-attachments/assets/e0bdc723-95a3-4ca0-883b-76ba5399421d)

**Comment by adashen** [comment]
Hi @iamyashikagoyal can you track the issue  at https://github.com/microsoft/teams-ai/issues/2132 ?  It seems a upstream issue, you can get more info there.

**Comment by iamyashikagoyal** [comment]
Every single issue is getting closed saying it is duplicate, but not even once my issue was resolved. I am simply downloaded the zip from azure ai studio, and extracted the zip, changed config jsons text embedding api key to mine and also for data source. Now you tell me what should i do next. 


No one from Microsoft is helping.

**Comment by iamyashikagoyal** [comment]
The bot is responding in testtool, local (with citations error) and for developer mode it is not working at all.

**Comment by rbertucat** [comment]
@iamyashikagoyal, in the file `package.json`, update the versions of `@microsoft/teams-ai` to 1.5.3 and of `openai` to 4.68.2 as described here: https://github.com/microsoft/teams-ai/issues/2060#issuecomment-2433038912.

It should fix your citations issue.

**Comment by IAM5K** [comment]
@iamyashikagoyal there are lots of thing which works in testtool but when it is tested in local or prod then the outputs can be different than expected.
For example the amount of data we can hold/ attach to adaptive cards

**Comment by iamyashikagoyal** [comment]
@rbertucat Quick Question. Do you want me to change the versions to look exactly like the image, or just change the teamsai and openai and run npm i in the terminal.

**Comment by iamyashikagoyal** [comment]
So, if i buy a domain xyz.com, how can i map it with the app. Can you refer any doc or steps i should follow. Like where will i be able to see the cname and how will i add it? Please help me here, i really think this is the point where i am getting stuck. i believe if i do this correctly, i can make this thing work.

**Comment by iamyashikagoyal** [comment]
@rbertucat Thank you so much the citations made the bot working perfectly in local env. @IAM5K @rbertucat is there any possible way, i can just deploy the local env as my final app? Because the dev is still giving errors. But maybe if i can just publish local env manifest? Will that help and how can i do it?

**Comment by iamyashikagoyal** [comment]
@adashen I am still not able to publish my bot in dev-mode. It is still showing me the same error. Bot encountered an error.

**Comment by anchenyi** [comment]
> @rbertucat Thank you so much the citations made the bot working perfectly in local env. @IAM5K @rbertucat is there any possible way, i can just deploy the local env as my final app? Because the dev is still giving errors. But maybe if i can just publish local env manifest? Will that help and how can i do it?

hi @iamyashikagoyal, to deploy the local env as the final app, you can go to the Developer Portal [(link)](https://dev.teams.microsoft.com/apps). If you've run the local app in Teams Toolkit, you'll see it listed in the Developer Portal. Click your app, then click the "Publish" button in the top-right corner to submit it for the tenant admin's review. You can also click the "Preview in Teams" to test your app in Teams.

**Comment by iamyashikagoyal** [comment]
@anchenyi It is still not responding after publishing it. So turns out we have to get it in dev only. Can you help me understanding why it is working on Local env and not on developer environment?

Here is the env for both:
Local Env (Working):
BOT_ENDPOINT=https://q761f0rc-3978.usw3.devtunnels.ms
BOT_DOMAIN=q761f0rc-3978.usw3.devtunnels.ms
TEAMSFX_ENV=local
APP_NAME_SUFFIX=local
TEAMS_APP_ID=d58.....f
TEAMS_APP_TENANT_ID=ef0a.....1
BOT_ID=fb.....f3
AZURE_OPENAI_ENDPOINT=https://grfsbotassista7976386133.openai.azure.com/
AZURE_OPENAI_DEPLOYMENT=gpt-4
BOT_OBJECT_ID=d6c.....1f0e


Dev Env (Not Working):
# This file includes environment variables that will be committed to git by default.

# Built-in environment variables
TEAMSFX_ENV=dev

# Updating AZURE_SUBSCRIPTION_ID or AZURE_RESOURCE_GROUP_NAME after provision may also require an update to RESOURCE_SUFFIX, because some services require a globally unique name across subscriptions/resource groups.
AZURE_SUBSCRIPTION_ID=b32......ad
AZURE_RESOURCE_GROUP_NAME=G......NT
RESOURCE_SUFFIX=99687c

# Generated during provision, you can also add your own variables.
BOT_ID=2f57ff94-fa3c-4706-bf6c-832c06a37fa5
BOT_PASSWORD=
APP_NAME_SUFFIX=dev
TEAMS_APP_ID=cdb6f04f-3f41-4524-8321-614f3969b365
TEAMS_APP_TENANT_ID=ef0......11
BOT_AZURE_APP_SERVICE_RESOURCE_ID=/subscriptions/b32.....687c
BOT_ENDPOINT=https://grfs-99687c.azurewebsites.net/api/messages
BOT_DOMAIN=grfs-99687c.azurewebsites.net
AZURE_OPENAI_ENDPOINT=https://grfsbotassista7976386133.openai.azure.com/
AZURE_OPENAI_DEPLOYMENT=gpt-4
BOT_TENANT_ID=ef0ae.....2d11
BOT_OBJECT_ID=6da861.....cf2

**Comment by anchenyi** [comment]
hi @yukun-dong, could you help with this?

**Comment by yukun-dong** [comment]
Hi @iamyashikagoyal , from your screenshot, it appears that the bot successfully sent out the welcome message. This suggests that the remote bot configuration is likely correct, and the issue may be elsewhere.

Could you please share your project with us so we can take a look into it?

**Comment by iamyashikagoyal** [comment]
@yukun-dong I am more than happy to get this issue resolved, but how should i share my project, is it possible if you can give me the link to upload the zip, how like how should i share?

**Comment by yukun-dong** [comment]
> @yukun-dong I am more than happy to get this issue resolved, but how should i share my project, is it possible if you can give me the link to upload the zip, how like how should i share?

Is it of for you to add the zip in the comment? Just don't include the env files in the zip.

**Comment by iamyashikagoyal** [comment]
@yukun-dong I am trying to upload a zip, It says : File size too big: 25 MB are allowed, 83 MB were attempted to upload.

**Comment by yukun-dong** [comment]
Hi @iamyashikagoyal, I’ve reviewed your project, and your Azure bot is configured correctly—it’s able to return messages, as shown here:
![image](https://github.com/user-attachments/assets/9d8b6dfd-f32c-4e5e-9944-ac47ffdd7713)

I haven’t looked deeply into your Azure OpenAI logic, but I think there may be an issue with your dev environment configuration. This could be causing the discrepancy between local and dev environments. Please double-check that the necessary variables (such as AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_DEPLOYMENT, etc.) are included in env.dev and have been added to the environment settings in your App Service.

**Comment by iamyashikagoyal** [comment]
@yukun-dong I have uploaded my env. folder also, if you want to take a look. I don't know why but dev env is not working. You know, it is automatically getting populated after getting provisioned. They automatically fill up, i literally have not changed anything in the env

**Comment by yukun-dong** [comment]
@iamyashikagoyal seems you didn't add AZURE_OPENAI_API_KEY into your dev env. Also your biceps didn't add AZURE_OPENAI_API_KEY into env settings. Did you use AZURE_OPENAI_API_KEY in your local env?

If so, that may be the reason of your dev env not working. You can go to portal-> your app service->settings-> environment variables, then add AZURE_OPENAI_API_KEY like below:
![image](https://github.com/user-attachments/assets/c8590973-6394-42fc-a691-dc1bb87fccec)
After that, please restart the app service and try test again.

**Comment by iamyashikagoyal** [comment]
@yukun-dong I tried adding it in both the portal and in the code present inside teams toolkit (vs code), It is still giving the same error. Also, No, my local didnt have AZURE_OPENAI_API_KEY.
ENV Folder:
https://drive.google.com/drive/folders/1QpBUrK5sPiqJC9J4KPV0kPwszdmUv89W?usp=sharing

![Screenshot 2024-11-05 200133](https://github.com/user-attachments/assets/c25f3781-e0b6-4df6-abd6-e92371718bc8)
![Screenshot 2024-11-05 200144](https://github.com/user-attachments/assets/af1ae65e-2d05-45c7-9327-1f8e06a6f1e1)

**Comment by yukun-dong** [comment]
@iamyashikagoyal This is something I am unfamiliar with. Could you check the detailed error message in logs and see if there are any insights?

To enable log stream, go to your app service-> monitoring-> app service logs, adjust the settings like below: 
![image](https://github.com/user-attachments/assets/8a06eb1c-1ad9-4966-b739-81658de4c91c)
Then, go to the log stream, try entering something in the Teams bot, and check for any log messages that appear.

**Comment by iamyashikagoyal** [comment]
Connected!
2024-11-06T04:38:30  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).OpenAIModel: The 'requestConfig' option is deprecated. Use 'clientOptions' instead.(node:1040) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `node --trace-deprecation ...` to show where the warning was created)(node:1040) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>IIS Detailed Error - 404.0 - Not Found</title><style type="text/css"></style></head><body><div id="content"><div class="content-container"><h3>HTTP Error 404.0 - Not Found</h3><h4>The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul> 	<li>The directory or file specified does not exist on the Web server.</li> 	<li>The URL contains a typographical error.</li> 	<li>A custom filter or module, such as URLScan, restricts access to the file.</li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Things you can try:</h4><ul> 	<li>Create the content on the Web server.</li> 	<li>Review the browser URL.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code and see which module is calling SetStatus. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Detailed Error Information:</h4><div id="details-left"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr><tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr><tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr><tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr></table></div><div id="details-right"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://GRFS-99687c:80/lib/index.js</td></tr><tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\home\site\wwwroot\lib\index.js</td></tr><tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr><tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr></table><div class="clear"></div></div></fieldset></div><div class="content-container"><fieldset><h4>More Information:</h4>This error means that the file or directory does not exist on the server. Create the file or directory and try the request again.<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=404,0,0x00000000,20348">View more information &raquo;</a></p><p>Microsoft Knowledge Base Articles:</p></fieldset></div></div></body></html><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>IIS Detailed Error - 404.0 - Not Found</title><style type="text/css"></style></head><body><div id="content"><div class="content-container"><h3>HTTP Error 404.0 - Not Found</h3><h4>The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul> 	<li>The directory or file specified does not exist on the Web server.</li> 	<li>The URL contains a typographical error.</li> 	<li>A custom filter or module, such as URLScan, restricts access to the file.</li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Things you can try:</h4><ul> 	<li>Create the content on the Web server.</li> 	<li>Review the browser URL.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code and see which module is calling SetStatus. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Detailed Error Information:</h4><div id="details-left"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr><tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr><tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr><tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr></table></div><div id="details-right"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://GRFS-99687c:80/lib/index.js</td></tr><tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\home\site\wwwroot\lib\index.js</td></tr><tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr><tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr></table><div class="clear"></div></div></fieldset></div><div class="content-container"><fieldset><h4>More Information:</h4>This error means that the file or directory does not exist on the server. Create the file or directory and try the request again.<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=404,0,0x00000000,20348">View more information &raquo;</a></p><p>Microsoft Knowledge Base Articles:</p></fieldset></div></div></body></html>[35;1mCHAT PROMPT:[0m[{"role": "system","content": "# Note\n// To update the model instructions directing how your custom copilot should behave when generating a response, \n// please update the role_information parameter located in the src\\prompts\\chat\\config.json file.\n// The skprompt.txt file is not used by Azure OpenAI On Your Data.\n"},{"role": "user","content": "hi"}]AuthenticationError: 401 Principal does not have access to API/Operation.at APIError.generate (C:\home\site\wwwroot\node_modules\openai\error.js:48:20)at AzureOpenAI.makeStatusError (C:\home\site\wwwroot\node_modules\openai\core.js:293:33)at AzureOpenAI.makeRequest (C:\home\site\wwwroot\node_modules\openai\core.js:337:30)at process.processTicksAndRejections (node:internal/process/task_queues:95:5)at async OpenAIModel.completePrompt (C:\home\site\wwwroot\node_modules\@microsoft\teams-ai\lib\models\OpenAIModel.js:170:32)at async LLMClient.callCompletePrompt (C:\home\site\wwwroot\node_modules\@microsoft\teams-ai\lib\planners\LLMClient.js:210:31)at async LLMClient.completePrompt (C:\home\site\wwwroot\node_modules\@microsoft\teams-ai\lib\planners\LLMClient.js:176:30)at async ActionPlanner.completePrompt (C:\home\site\wwwroot\node_modules\@microsoft\teams-ai\lib\planners\ActionPlanner.js:176:16)at async ActionPlanner.continueTask (C:\home\site\wwwroot\node_modules\@microsoft\teams-ai\lib\planners\ActionPlanner.js:104:24)at async ActionPlanner.beginTask (C:\home\site\wwwroot\node_modules\@microsoft\teams-ai\lib\planners\ActionPlanner.js:79:16) {status: 401,headers: {'apim-request-id': '4b03bcd1-5e4a-42fb-bffe-746c36783fb0','content-length': '99','content-type': 'application/json',date: 'Wed, 06 Nov 2024 04:39:23 GMT','strict-transport-security': 'max-age=31536000; includeSubDomains; preload','x-content-type-options': 'nosniff','x-ms-client-request-id': 'Not-Set'},request_id: undefined,error: {code: 'PermissionDenied',message: 'Principal does not have access to API/Operation.'},code: 'PermissionDenied',param: undefined,type: undefined}[35;1mERROR:[0m[32m401 Principal does not have access to API/Operation.[0m[35;1mHEADERS:[0m{"apim-request-id": "4b03bcd1-5e4a-42fb-bffe-746c36783fb0","content-length": "99","content-type": "application/json","date": "Wed, 06 Nov 2024 04:39:23 GMT","strict-transport-security": "max-age=31536000; includeSubDomains; preload","x-content-type-options": "nosniff","x-ms-client-request-id": "Not-Set"}


### Its a huge error showing up @yukun-dong

**Comment by yukun-dong** [comment]
Hi @iamyashikagoyal, the error message "AuthenticationError: 401 Principal does not have access to API" suggests this may be an authentication issue with Azure OpenAI. We currently have limited expertise on this topic, but we’ll do our best to find relevant docs and will keep you updated if we uncover anything helpful.

In the meantime, please feel free to reach out to the Azure OpenAI side for assistance, they may be able to provide further insights.

**Comment by iamyashikagoyal** [comment]
Sure @yukun-dong, But please let me know if you see anything.

**Comment by wh-alice** [comment]
Close stale issues. Please create new issue then we can support.
