### ISSUE TITLE
Failed deployments and provisioning: Issue with azureStorage/enableStaticWebsite during lifecycle provision

### ISSUE THREAD

**Issue by IAM5K** [OfficeDev/teams-toolkit#12571]
**Description**:
During the execution of the lifecycle provision for my Teams app deployment, I encountered an error with the `azureStorage/enableStaticWebsite` step. It seems to be related to fetching properties of the container `$web` in an Azure Storage Account.

**Logs**:
```
[2024-10-20T10:05:05.764Z] [Error] - Failed to execute lifecycle provision due to failed action: azureStorage/enableStaticWebsite.
gvr:Unable to get properties of container '$web' in Azure Storage Account 'xxxxxx' due to error: 
{"stack":"TypeError: Expected signal to be an instanceof AbortSignal\n\tat new e (/home/xxxx/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.10.0/out/src/extension.js:243:339157)\n\tat /home/xxxx/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.10.0/out/src/extension.js:243:327918\n\tat new Promise (<anonymous>)\n\tat i0e (/home/xxxx/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.10.0/out/src/extension.js:243:327882)\n\tat m1e.fetch (/home/xxxx/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.10.0/out/src/extension.js:790:3897)\n\tat m1e.sendRequest (/home/xxxx/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.10.0/out/src/extension.js:790:2282)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n\tat async xlt.attemptSendRequest (/home/xxxx/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.10.0/out/src/extension.js:792:9894)\n\tat async Vce.sendOperationRequest (/home/xxxx/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.10.0/out/src/extension.js:791:27805)\n\tat async e.getProperties (/home/xxxx/.vscode/extensions/teamsdevapp.ms-teams-vscode-extension-5.10.0/out/src/extension.js:801:2566)"
```

**Summary**:
- Lifecycle provision was successfully executed for actions such as `aadApp/create` and `arm/deploy`.
- However, the `azureStorage/enableStaticWebsite` action failed with a TypeError related to an `AbortSignal`.

**Environment**:
- Azure Storage Account: `xxxxxx`
- Teams App ID: `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
- Bot ID: `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
- Extension Version: `5.10.0`

**Steps to Reproduce**:
1. Execute lifecycle provision using the existing configurations.
2. The issue occurs at the `azureStorage/enableStaticWebsite` step when attempting to fetch container properties.

**VS Code Extension Information**:
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.11-amd64

**Teams Toolkit**
v5.10.0

**Expected Behavior**:
The provisioning should complete without error, and the static website should be enabled.

**Actual Behavior**:
Provisioning fails due to the `TypeError: Expected signal to be an instanceof AbortSignal`.

**Comment by Siglud** [comment]
Sorry, there is a bug related to 5.10.0 because of the version of `@azure/core-http` has been changed. 

I've created a fix to solve this problem. https://github.com/OfficeDev/teams-toolkit/pull/12583

**Comment by IAM5K** [comment]
Since the PR is merged, is it safe to update the extension?

**Comment by Siglud** [comment]
We still need to wait next release to bring this fix public. The next pre-release version will start at the middle of the Nov.

**Comment by IAM5K** [comment]
![image](https://github.com/user-attachments/assets/8ba201a3-54d9-4f26-b3c7-05762cf60718)

recently we started getting this error, with the package we discussed earlier. 
I had deployed the application by downgrading my teams toolkit.
Do you suspect any issue or relation to the package you changed.

**Comment by Siglud** [comment]
The PR that I created are still in the release progress and will publish a pre-release version in this week.

As for this issue you mentioned, it looks like your code want to retrieve some data from Azure? Maybe you should switch to `@azure/core-rest-pipeline` instead of `@azure/core-http` because it's no longer supported. See https://www.npmjs.com/package/@azure/core-http/

**Comment by yukun-dong** [comment]
> Thanks for the confirmation/support @ls-msc , I also tried to switch back and provision works there but the deployment fails. Also the `@microsoft/adaptivecards-tools` is missing in the new upgrade
> 
> ```
> [2024-10-23T08:55:47.681Z] [Info] -  [script stdout] node_modules/adaptivecards-templating/lib/json-schema-card.d.ts(1,31): error TS2307: Cannot find module 'adaptivecards/src/schema' or its corresponding type declarations.
> src/TeamsBot.ts(1,31): error TS2307: Cannot find module '@microsoft/adaptivecards-tools' or its corresponding type declarations.
> src/commands/wish.ts(2,31): error TS2307: Cannot find module '@microsoft/adaptivecards-tools' or its corresponding type declarations.
> ```
> 
> We need to manually install the package. For now this is a work around but not the solution for all.
> 
> This issue will confuse those who initialized the project with v 5.10.0. They will never know what can be the cause of failing provision and deployment.

Hi @IAM5K , for the adaptive-card-tools issue, could you please kindly provide the name of the template/sample you are using? Thanks.

**Comment by IAM5K** [comment]
@yukun-dong , my project is about 2 years old and we have been updating our packages or dependency regularly.
After updating to the latest teams tooklit this package was marked as missing.
i added it manually and now the flow is working but it has deprecated warning.
```
        "@microsoft/adaptivecards-tools": "^1.3.5",
```
This package was not required separately, but now it is required and the `adaptivecard.declare` is now deprecated.
```typescript
export class HelpCommandHandler implements TeamsFxBotCommandHandler {
  triggerPatterns: TriggerPatterns = "help";
  async handleCommandReceived(
    context: TurnContext,
    message: CommandMessage
  ): Promise<string | Partial<Activity> | void> {
    console.log(`Bot received message: ${message.text}`);
    const cardJson = AdaptiveCards.declare(helpCard).render();
    return MessageFactory.attachment(CardFactory.adaptiveCard(cardJson));
  }
}
```

**Comment by yukun-dong** [comment]
@IAM5K This change is intentional, as we plan to deprecate the "@microsoft/adaptivecards-tools" package in 2025. For more details, please refer to this [post](https://devblogs.microsoft.com/microsoft365dev/streamline-your-workflow-embracing-adaptive-cards-templating/). If you'd like to continue using the package without deprecation warnings, please use a version prior to 1.3.4.

**Comment by monty0007** [comment]
[2025-05-06T09:53:31.427Z] [Error] - code:botFrameworkCreate.Itt, message: An unexpected error has occurred while performing the botFrameworkCreate task. {"stack":"ForbiddenResultBotFrameworkError: Botframework provisioning returns forbidden result when attempting to create bot registration.\n    at Wv.handleBotFrameworkError (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:213:43353)\n    at Wv.createBotRegistration (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:213:42308)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Wv.<anonymous> (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:14:390190)\n    at o6c (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:879:454197)\n    at odt.handler (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:879:456462)\n    at c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:879:455792\n    at CWs (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:209:19725)\n    at odt.execute (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:879:455755)\n    at odt.<anonymous> (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:683:29790)\n    at executeImpl (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:717:4948)\n    at execute (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:717:2670)\n    at _Y.provision (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:821:14082)\n    at _Y.<anonymous> (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:14:390190)\n    at Id.provisionResources (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:920:18815)\n    at Id.GNc (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:883:23093)\n    at Id.a3c (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:883:27360)\n    at Id.i3c (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:883:26414)\n    at VNc (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:883:23065)\n    at Id.<anonymous> (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:883:22230)\n    at Id.Y7c (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:918:6512)\n    at Id.o3c (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:883:27659)\n    at Id.<anonymous> (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:14:390190)\n    at Hx (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:2497:19371)\n    at e1t._do (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:2511:7026)\n    at e.runWithTelemetryGeneric (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:682:859)\n    at e.runWithTelemetryProperties (c:\\Users\\ak149\\.vscode\\extensions\\teamsdevapp.ms-teams-vscode-extension-5.14.1\\out\\src\\extension.js:682:607)","message":"Botframework provisioning returns forbidden result when attempting to create bot registration.","name":"ForbiddenResultBotFrameworkError","details":["Botframework provisioning returns forbidden result when attempting to create bot registration.","Botframework provisioning returns forbidden result when attempting to create bot registration."],"suggestions":["Please check log-in Output panel and try to fix this issue.","Retry the current step."],"errorType":"User"}

**Comment by Siglud** [comment]
> [2025-05-06T09:53:31.427Z] [Error] - code:botFrameworkCreate.Itt, message: An unexpected error has occurred while performing the botFrameworkCreate task. {"stack":"ForbiddenResultBotFrameworkError: Botframework provisioning returns forbidden result when attempting to create bot registration.\n at Wv.handleBotFrameworkError (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:213:43353)\n at Wv.createBotRegistration (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:213:42308)\n at processTicksAndRejections (node:internal/process/task_queues:95:5)\n at Wv. (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:14:390190)\n at o6c (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:879:454197)\n at odt.handler (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:879:456462)\n at c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:879:455792\n at CWs (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:209:19725)\n at odt.execute (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:879:455755)\n at odt. (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:683:29790)\n at executeImpl (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:717:4948)\n at execute (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:717:2670)\n at _Y.provision (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:821:14082)\n at _Y. (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:14:390190)\n at Id.provisionResources (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:920:18815)\n at Id.GNc (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:883:23093)\n at Id.a3c (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:883:27360)\n at Id.i3c (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:883:26414)\n at VNc (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:883:23065)\n at Id. (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:883:22230)\n at Id.Y7c (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:918:6512)\n at Id.o3c (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:883:27659)\n at Id. (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:14:390190)\n at Hx (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:2497:19371)\n at e1t._do (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:2511:7026)\n at e.runWithTelemetryGeneric (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:682:859)\n at e.runWithTelemetryProperties (c:\Users\ak149\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-5.14.1\out\src\extension.js:682:607)","message":"Botframework provisioning returns forbidden result when attempting to create bot registration.","name":"ForbiddenResultBotFrameworkError","details":["Botframework provisioning returns forbidden result when attempting to create bot registration.","Botframework provisioning returns forbidden result when attempting to create bot registration."],"suggestions":["Please check log-in Output panel and try to fix this issue.","Retry the current step."],"errorType":"User"}

This error was thrown by the backend service. It should be ok now.

**Comment by wh-alice** [comment]
Close stale issues. Please create new issue then we can support.
